3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix AS1 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/anterior_Salience/01/1.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix AS2 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/anterior_Salience/02/2.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix AS3 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/anterior_Salience/03/3.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix AS4 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/anterior_Salience/04/4.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix AS5 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/anterior_Salience/05/5.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix AS6 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/anterior_Salience/06/6.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix AS7 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/anterior_Salience/07/7.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix AS -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/anterior_Salience/anterior_Salience.nii.gz
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix A1 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/Auditory/01/1.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix A2 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/Auditory/02/2.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix A3 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/Auditory/03/3.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix A -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/Auditory/Auditory.nii.gz
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix BG1 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/Basal_Ganglia/01/1.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix BG2 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/Basal_Ganglia/02/2.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix BG3 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/Basal_Ganglia/03/3.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix BG4 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/Basal_Ganglia/04/4.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix BG5 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/Basal_Ganglia/05/5.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix BG -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/Basal_Ganglia/Basal_Ganglia.nii.gz
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix DDMN1 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/dorsal_DMN/01/1.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix DDMN2 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/dorsal_DMN/02/2.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix DDMN3 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/dorsal_DMN/03/3.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix DDMN4 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/dorsal_DMN/04/4.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix DDMN5 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/dorsal_DMN/05/5.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix DDMN6 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/dorsal_DMN/06/6.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix DDMN7 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/dorsal_DMN/07/7.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix DDMN8 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/dorsal_DMN/08/8.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix DDMN9 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/dorsal_DMN/09/9.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix DDMN -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/dorsal_DMN/dDMN.nii.gz
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix HV1 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/high_Visual/01/1.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix HV2 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/high_Visual/02/2.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix HV -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/high_Visual/high_Visual.nii.gz
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix L1 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/Language/01/1.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix L2 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/Language/02/2.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix L3 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/Language/03/3.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix L4 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/Language/04/4.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix L5 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/Language/05/5.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix L6 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/Language/06/6.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix L7 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/Language/07/7.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix L -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/Language/Language.nii.gz
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix LECN1 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/LECN/01/1.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix LECN2 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/LECN/02/2.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix LECN3 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/LECN/03/3.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix LECN4 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/LECN/04/4.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix LECN5 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/LECN/05/5.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix LECN6 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/LECN/06/6.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix LECN -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/LECN/LECN.nii.gz
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix PS1 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/post_Salience/01/1.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix PS2 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/post_Salience/02/2.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix PS3 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/post_Salience/03/3.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix PS4 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/post_Salience/04/4.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix PS5 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/post_Salience/05/5.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix PS6 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/post_Salience/06/6.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix PS7 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/post_Salience/07/7.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix PS8 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/post_Salience/08/8.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix PS9 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/post_Salience/09/9.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix PS10 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/post_Salience/10/10.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix PS11 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/post_Salience/11/11.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix PS12 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/post_Salience/12/12.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix PS -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/post_Salience/post_Salience.nii.gz
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix P1 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/Precuneus/01/1.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix P2 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/Precuneus/02/2.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix P3 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/Precuneus/03/3.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix P4 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/Precuneus/04/4.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix P -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/Precuneus/Precuneus.nii.gz
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix PV1 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/prim_Visual/01/1.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix PV2 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/prim_Visual/02/2.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix PV -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/prim_Visual/prim_Visual.nii.gz
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix RECN1 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/RECN/01/1.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix RECN2 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/RECN/02/2.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix RECN3 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/RECN/03/3.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix RECN4 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/RECN/04/4.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix RECN5 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/RECN/05/5.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix RECN6 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/RECN/06/6.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix RECN -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/RECN/RECN.nii.gz
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix S1 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/Sensorimotor/01/1.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix S2 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/Sensorimotor/02/2.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix S3 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/Sensorimotor/03/3.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix S4 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/Sensorimotor/04/4.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix S5 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/Sensorimotor/05/5.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix S6 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/Sensorimotor/06/6.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix S -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/Sensorimotor/Sensorimotor.nii.gz
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix VDMN1 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/ventral_DMN/01/1.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix VDMN2 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/ventral_DMN/02/2.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix VDMN3 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/ventral_DMN/03/3.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix VDMN4 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/ventral_DMN/04/4.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix VDMN5 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/ventral_DMN/05/5.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix VDMN6 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/ventral_DMN/06/6.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix VDMN7 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/ventral_DMN/07/7.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix VDMN8 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/ventral_DMN/08/8.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix VDMN9 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/ventral_DMN/09/9.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix VDMN10 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/ventral_DMN/10/10.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix VDMN -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/ventral_DMN/vDMN.nii.gz
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix VS1 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/Visuospatial/01/1.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix VS2 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/Visuospatial/02/2.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix VS3 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/Visuospatial/03/3.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix VS4 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/Visuospatial/04/4.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix VS5 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/Visuospatial/05/5.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix VS6 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/Visuospatial/06/6.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix VS7 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/Visuospatial/07/7.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix VS8 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/Visuospatial/08/8.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix VS9 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/Visuospatial/09/9.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix VS10 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/Visuospatial/10/10.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix VS11 -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/Visuospatial/11/11.nii
3dresample -master ~/TRANS_DC/aug2015_analysis/s313-TASKcomp.results/all_runs.s313-TASKcomp+tlrc -prefix VS -inset /home/mbezdek/TRANS_DC/aug2015_analysis/cluster_find/Visuospatial/Visuospatial.nii.gz




